# 오프라인/온라인 판매 데이터 통합하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131537
# 작성자: 장경민
# 작성일: 2026. 02. 24. 18:05:55

WITH TOTAL_SALE AS (
    SELECT 
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
        PRODUCT_ID, 
        USER_ID, 
        SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
    UNION ALL
    SELECT 
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
        PRODUCT_ID, 
        NULL as USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
)
SELECT 
    SALES_DATE, 
    PRODUCT_ID, 
    USER_ID, 
    SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM TOTAL_SALE
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID 
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;